### ISSUE TITLE
pulizia

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/Html#2]
ripulisci tutto per favore. Tutti questi effetti devi imparare a farli senza usare librerie varie (la tua cartella pesa 20M, ti pare normale?)

**Comment by Giandomenico-bit** [comment]
Volevo solo rendere più carine le pagine! Ma oggi giorno ci sono app che creano bellissimi siti anche senza scrivere interi codici HTML e CSS, tipo wordpress. O sbaglio?

**Comment by FabioZTessitore** [comment]
Sì ma tu studi informatica, vuoi imparare a fare o a usare? E cmq la tua
pagina è troppo pesante (20MB). Non è accettabile

Il dom 3 nov 2019, 14:58 Giandomenico-bit <notifications@github.com> ha
scritto:

**Comment by Giandomenico-bit** [comment]
Ho capito! Perdonate, come sempre, la mia superficialità nel fare le cose

**Comment by FabioZTessitore** [comment]
Tranquillo

Il dom 3 nov 2019, 15:20 Giandomenico-bit <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
problemi?

**Comment by Giandomenico-bit** [comment]
Prof. scusate se non ho più pubblicato codice, ma in questi giorni ho dovuto fare due esami e fra pochi giorni ho una prova in itinere di algebra. Quando potrò correggerò il codice Html.

**Comment by FabioZTessitore** [comment]
ok, perfetto
