### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/Html#3]
perché ci sono i br?

**Comment by Giandomenico-bit** [comment]
il tag <br> inserisce uno spazio tra una riga e l'altra

**Comment by Giandomenico-bit** [comment]
br

**Comment by FabioZTessitore** [comment]
Lo so, ma non va bene fatto così.
Con l'html devi preoccuparti della struttura della pagina, non di come
viene visualizzata.
Quindi o lasci così o metti i tag <a> in altri tag (ad es. paragrafi, lista)

Il lun 25 nov 2019, 15:28 Giandomenico-bit <notifications@github.com> ha
scritto:

**Comment by Giandomenico-bit** [comment]
ah ho capito!
